USE DB_project;
GO

INSERT INTO Library.Publishers (PublisherName) VALUES
(N'TechNova Press'),
(N'Global Scholarly Publishing'),
(N'Infiniti Books'),
(N'Nexus Academic'),
(N'Quantum Editions'),
(N'Aetherium Publishing'),
(N'Digital Horizons Media'),
(N'Cognito Publishing'),
(N'Synergy Academic Press'),
(N'MindSphere Books'),
(N'Evergreen Scholarly'),
(N'Apex Knowledge Group'),
(N'Frontier Learning Inc.'),
(N'Prime Meridian Press'),
(N'Celestial Research Pub.'),
(N'Echoes of Wisdom Ltd.'),
(N'Artemis Academic'),
(N'Beacon Hill Books'),
(N'Capitol University Press'),
(N'Discovery Source Pub.'),
(N'Echelon Texts'),
(N'Fusion Knowledgebase'),
(N'Genesis Scholarly'),
(N'Horizon Bookshelf'),
(N'Insightful Readings'),
(N'Jupiter Academic'),
(N'Keystone Learning'),
(N'Lumina Press'),
(N'Magnum Opus Editions'),
(N'Nova Vista Publications'),
(N'Omega Research Press'),
(N'Pinnacle Academic'),
(N'Quasar Books'),
(N'Radiant Minds Pub.'),
(N'Solstice Scholarly'),
(N'Titanium Texts'),
(N'Universal Knowledge Hub'),
(N'Vanguard Learning'),
(N'Whispering Pines Books'),
(N'Xenon Academic'),
(N'Yesteryear Press'),
(N'Zenith Research'),
(N'Axiom Academic Press'),
(N'Beta Literary Works'),
(N'Gamma Scholarly Pub.'),
(N'Delta Knowledge Systems'),
(N'Epsilon Academic Solutions'),
(N'Zeta Publishing House'),
(N'Eta Educational Books'),
(N'Theta Science Publishing'),
(N'Iota Research & Pub.');