USE DB_project;
GO

INSERT INTO Library.Borrowing (LibraryMemberID, BorrowedCopyID, LoanDate, ReturnDueDate) VALUES
(1, 1, DATEADD(DAY, -45, CAST(GETDATE() AS DATE)), DATEADD(DAY, -30, CAST(GETDATE() AS DATE))),  -- Overdue by 30 days
(2, 2, DATEADD(DAY, -30, CAST(GETDATE() AS DATE)), DATEADD(DAY, -15, CAST(GETDATE() AS DATE))),  -- Overdue by 15 days
(3, 3, DATEADD(DAY, -20, CAST(GETDATE() AS DATE)), DATEADD(DAY, -5, CAST(GETDATE() AS DATE))),   -- Overdue by 5 days
(4, 4, DATEADD(DAY, -10, CAST(GETDATE() AS DATE)), DATEADD(DAY, -1, CAST(GETDATE() AS DATE))),   -- Overdue by 1 day
(5, 5, DATEADD(DAY, -5, CAST(GETDATE() AS DATE)), DATEADD(DAY, 2, CAST(GETDATE() AS DATE))),    -- Due in 2 days
(6, 6, DATEADD(DAY, -3, CAST(GETDATE() AS DATE)), DATEADD(DAY, 5, CAST(GETDATE() AS DATE))),    -- Due in 5 days
(7, 7, DATEADD(DAY, -1, CAST(GETDATE() AS DATE)), DATEADD(DAY, 7, CAST(GETDATE() AS DATE))),    -- Due in 7 days
(8, 8, CAST(GETDATE() AS DATE), DATEADD(DAY, 14, CAST(GETDATE() AS DATE))),                     -- Due in 14 days
(9, 9, CAST(GETDATE() AS DATE), DATEADD(DAY, 14, CAST(GETDATE() AS DATE))),                     -- Due in 14 days
(10, 10, DATEADD(DAY, -7, CAST(GETDATE() AS DATE)), DATEADD(DAY, 7, CAST(GETDATE() AS DATE))),  -- Due in 7 days
(11, 11, DATEADD(DAY, -2, CAST(GETDATE() AS DATE)), DATEADD(DAY, 12, CAST(GETDATE() AS DATE))),  -- Due in 12 days
(12, 12, DATEADD(DAY, -10, CAST(GETDATE() AS DATE)), DATEADD(DAY, 4, CAST(GETDATE() AS DATE))), -- Due in 4 days
(13, 13, DATEADD(DAY, -25, CAST(GETDATE() AS DATE)), DATEADD(DAY, -10, CAST(GETDATE() AS DATE))), -- Overdue by 10 days
(14, 14, DATEADD(DAY, -35, CAST(GETDATE() AS DATE)), DATEADD(DAY, -20, CAST(GETDATE() AS DATE))), -- Overdue by 20 days
(15, 15, DATEADD(DAY, -8, CAST(GETDATE() AS DATE)), DATEADD(DAY, 6, CAST(GETDATE() AS DATE)));   -- Due in 6 days